### ISSUE TITLE
Missing make_timestamp

### ISSUE THREAD

**Issue by RTimothyEdwards** [billswartz7/UTD-BoxRouter#1]
Unable to compile due to missing "make_timestamp".  Was that supposed to be an included script, or a definition in the Makefile?

**Comment by billswartz7** [comment]
This program is does not build in a standalone fashion.    It is meant to be a program in the The-OpenRoad-Project suite and shares its infrastructure.    The make_timestamp exists in ../The-OpenRoad-Project/tools/bin directory.   Please see Tutu's Docker file for how to build this program.
