### ISSUE TITLE
Linking to tcl directory

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#2]
After building a release from "The-OpenROAD-Project", copying the openroad.release, untaring on a different computer and running . ./setup.sh, utdBoxRouter appears to run into some issues linking tcl

ERROR[UTDGUI_Tcl_init]:stack trace:Can't find a usable init.tcl in the following directories: 
    /build/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.8/library ./tcl8.6.8/library

In my example about "/build" is the prefix provided when configuring The-OpenROAD-Project.

utdBoxRouter should look for tcl8.6 in $OPENROAD/lib/.

The only way I am able to workaround this is to run the utdBoxRouter command with the $OPENROAD as the work directory

**Comment by billswartz7** [comment]
Please look at your build directory:
...build/modules/utd-gui/src/tcl/generic/run.sh
should look like:
"       if {[info exists env(OPENROAD)]} {\n"
"          lappend scripts {file join $env(OPENROAD) tcl libtcl}\n"
"       }\n"
~            

The Tcl library of the moved OPENROAD installation should look something similar to:
ls $OPENROAD/tcl/libtcl
./             clock.tcl      http/          msgcat/        parray.tcl     tclIndex       word.tcl
../            dde/           http1.0/       msgs/          platform/      tcltest/
auto.tcl       encoding/      init.tcl       opt/           reg/           tm.tcl
auto.tcl.in    history.tcl    license.terms  package.tcl    safe.tcl       tzdata/

If it doesn't, then the copy of the tcl installation is not correct.   If this does exist, I will need more information.

**Comment by tajayi** [comment]
There is no file named `run.sh` but there is a `runenv.h` with similar contents.
```
[root@5d5392a9784b The-OpenROAD-Project]# ls -a build/modules/utd-gui/src/tcl/generic/
.  ..  runenv.h
[root@5d5392a9784b The-OpenROAD-Project]# cat build/modules/utd-gui/src/tcl/generic/runenv.h 
"       if {[info exists env(OPENROAD)]} {\n"
"          lappend scripts {file join $env(OPENROAD) tcl libtcl}\n"
"       }\n"
```



The OpenROAD installation direction seems to have all the files you listed (and more):
```
[ajayi@vlsipool-j12 OpenROAD-2019-05-13_13-18]$ ls -a tcl/libtcl/
.            dde          http1.0        opt          reg       tzdata
..           encoding     init.tcl       package.tcl  safe.tcl  word.tcl
auto.tcl     .gitignore   license.terms  parray.tcl   tclIndex
auto.tcl.in  history.tcl  msgcat         platform     tcltest
clock.tcl    http         msgs           RCS          tm.tcl
```
You can find the latest release of the installation at https://github.com/The-OpenROAD-Project/CI/releases/tag/v2019-05-13_13-18

**Comment by billswartz7** [comment]
Sorry about the name.  It is indeed runenv.h and that is indeed the problem.   I looked at the created library and it has UTDGUI instead of OPENROAD because there are two copies of runenv.h floating around.    I have modified the offending Makefile to always delete the bogus one if it ever shows up again and now I am testing.

**Comment by billswartz7** [comment]
Updated repository and tested it.   After build

strings libopenroad_tcl8.6.a | grep OPENROAD

should yield
       if {[info exists env(OPENROAD)]} {
          lappend scripts {file join $env(OPENROAD) tcl libtcl}

if build was correct.

**Comment by tajayi** [comment]
Thanks Bill. I'll rebuild

**Comment by tajayi** [comment]
Validated
