### ISSUE TITLE
Getting ispd18 style outputs

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#3]
Can you please provide a set of options or parameters that help achieve a similar route guides to those provided by the ispd18 contest? I am currently looking to use it as an input to UCSD's detail router.
I am also including @bangqi in this conversation

I am currently focused on the sample case from ispd18. On running UCSD's detail router (the version of it that only does a check - https://vlsicad.ucsd.edu/~bangqixu/toDaeyeon/), it has a few errors

```
net net1237
Error: pin inst4678/Y not covered by guide
Error: pin inst5638/A not covered by guide
Warning: net1237 2 pin not visited, fall back to feedrough mode
Error: net1237 2 pin not visited #guides = 4
Error: critical error guide not connected for net1237, exit now 1!
```
I'll let Bangqi elaborate on the errors.

There appears to be several undocumented parameters that I can be passed to utdBoxRouter. 

Find attached all the logs/files passed into utdBox router, and global route checker
[t11_gr.tar.gz](https://github.com/billswartz7/UTD-BoxRouter/files/3175220/t11_gr.tar.gz)

edit:
Note that my scripts automatically deletes the first line "UNITS DISTANCE MICRONS 1000 ;" which UCSD's router doesn't like

**Comment by billswartz7** [comment]
The fix was easy as it was a one line mistake.   However,  more graphics debug code was added to BoxRouter.     This fix was also verified using TimberWolfDR.     See picture for new draw guides feature in the global router when in graphics mode.

/Users/bill/Desktop/draw_guides.png

**Comment by tajayi** [comment]
Thanks Bill. I'll give it a try

**Comment by tajayi** [comment]
I am still getting similar errors with the new build

```
net net1237
Error: pin inst4678/Y not covered by guide
Error: pin inst5638/A not covered by guide
Warning: net1237 2 pin not visited, fall back to feedrough mode
Error: net1237 2 pin not visited #guides = 4
Error: critical error guide not connected for net1237, exit now 1!
```

Attached logs
[t11_gr.tar.gz](https://github.com/billswartz7/UTD-BoxRouter/files/3180446/t11_gr.tar.gz)

**Comment by billswartz7** [comment]
Here are pictures to the routing.   It was good that I wrote code to read the output guides and display them.    Clearly, you can see the pins are indeed covered.

![layer4](https://user-images.githubusercontent.com/30846759/57749700-c4cd1700-76a4-11e9-8e9b-04f3631818b5.png)
![layer3](https://user-images.githubusercontent.com/30846759/57749689-b7b02800-76a4-11e9-8e4a-a35c8648d339.png)

![layer2](https://user-images.githubusercontent.com/30846759/57749708-d3b3c980-76a4-11e9-9887-201ef44ca1d4.png)
![layer1](https://user-images.githubusercontent.com/30846759/57749718-e0382200-76a4-11e9-9779-16bdb524f459.png)

**Comment by tajayi** [comment]
This issue is resolved. It was due to a mismatching units. I updated it to 2000 in the gdo file and was able to get the global router checker from UCSD passing
