### ISSUE TITLE
utdBoxRouter fails to generate guides for several ISPD18 tests

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#6]
The global router fails to generate routing guides for ispd18 testss 3-10 - they all fail with segmentation errors. The following guides were successfully generated
ispd18_sample.guide - 0.3 seconds
ispd18_sample2.guide - 0.3 seconds
ispd18_sample3.guide - 18.6 seconds
ispd18_test1.guide - 32.3 seconds
ispd18_test2.guide - 4914.8 seconds

Find attached the logs/results from the run as well as the gdo scripts used.

[ispd_debug.tar.gz](https://github.com/billswartz7/UTD-BoxRouter/files/3187678/ispd_debug.tar.gz)

**Comment by billswartz7** [comment]
Problems have been reproduced.   Isolated the problems to be an issue with FLUTE and large net sizes.  Investigating

**Comment by billswartz7** [comment]
The problem is indeed FLUTE and large nets.   Flute algorithm put everything on the stack in a recursive algorithm which is a very poor technique.   Rewriting offending routines.

**Comment by billswartz7** [comment]
Rewrote FLUTE to be reentrant and dynamic.   Now no MAXD definition and totally dynamic.  
# UTD-flute
FLUTE repository
This repository contains the original flute (unused) and a streamlined
version which is reentrant and dynamic, that is MAXD has been completely
eliminated.   In addition, there are no known memory leaks and the
library has been tested using Purify.  Originally, FLUTE was written
using stack memory and was subject to stack size limitations.  It
was observed that this coding could fail with net sizes as small as
345 with MAXD set to 1000 and was input dependent.  This library
does not encode the lookup tables into the binary but reads them
from files.   The advantage is that 29MB of memory can be freed when
the flute object is freed.

Here are some results running on a 2014 Mac 2.8Ghz Intel Core i7 with
16GB DDR3 RAM:

 Number of Pins          Running Time in Milliseconds       Memory Usage
 --------------          ----------------------------                   -----------
   1,000,000                     6,152,125                                  298MB
     100,000                         509,173                                    56MB
      10,000                           45,238                                     32MB
       1,000                              3,842                                     29MB
         100                                  196                                     29MB
          10                                      0* 0.002 note 1                29MB
           2                                       0* 0.000062 note 2          29MB

Note 1: too small for interrupt timer.  Calculated 2ms / 1000 calls
Note 2: too small for interrupt timer.  Calculated 62ms / 1,000,000 calls

**Comment by tajayi** [comment]
Thanks Bill. I kicked of another round of testing

**Comment by tajayi** [comment]
Some progress on the ispd18 test cases. The latest results I have, as of this morning:

ispd18_sample 0.3 seconds (0:00)
ispd18_sample2  0.3 seconds (0:00)
ispd18_sample3  19.1 seconds (0:00)
ispd18_test1  36.8 seconds (0:00)
ispd18_test2  5876.0 seconds (1:37)
ispd18_test3  8403.2 seconds (2:20)
ispd18_test4  13411.2 seconds (3:43)
ispd18_test5  18348.9 seconds (5:05)
ispd18_test6  13657.9 seconds (3:47)
ispd18_test9  27355.1 seconds (7:35)
test 7,8 and 10 were killed after running for more than 12 hours

I am using the same script file for all tests. Is there a set of recommended options that may apply to all ispd18 tests?

Thanks

**Comment by billswartz7** [comment]
Hi Tutu,

You didn't wait long enough. They will finish.

Best,

Bill

On May 20, 2019 6:01:34 AM Tutu Ajayi <notifications@github.com> wrote:
> Some progress on the ispd18 test cases. The latest results I have, as of 
> this morning:
> ispd18_sample 0.3 seconds (0:00)
> ispd18_sample2 0.3 seconds (0:00)
> ispd18_sample3 19.1 seconds (0:00)
> ispd18_test1 36.8 seconds (0:00)
> ispd18_test2 5876.0 seconds (1:37)
> ispd18_test3 8403.2 seconds (2:20)
> ispd18_test4 13411.2 seconds (3:43)
> ispd18_test5 18348.9 seconds (5:05)
> ispd18_test6 13657.9 seconds (3:47)
> ispd18_test9 27355.1 seconds (7:35)
> test 7,8 and 10 were killed after running for more than 12 hoursI am using 
> the same script file for all tests. Is there a set of recommended options 
> that may apply to all ispd18 tests?
> Thanks
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by billswartz7** [comment]
Hi Tutu,

I don't know the best settings.  I thought this was going to be learned.  
BoxRouter is an ILP based router and running time is due to the solvers.  
The large nets that are now present slow it down tremendously.

Best,

Bill

On May 20, 2019 6:01:34 AM Tutu Ajayi <notifications@github.com> wrote:
> Some progress on the ispd18 test cases. The latest results I have, as of 
> this morning:
> ispd18_sample 0.3 seconds (0:00)
> ispd18_sample2 0.3 seconds (0:00)
> ispd18_sample3 19.1 seconds (0:00)
> ispd18_test1 36.8 seconds (0:00)
> ispd18_test2 5876.0 seconds (1:37)
> ispd18_test3 8403.2 seconds (2:20)
> ispd18_test4 13411.2 seconds (3:43)
> ispd18_test5 18348.9 seconds (5:05)
> ispd18_test6 13657.9 seconds (3:47)
> ispd18_test9 27355.1 seconds (7:35)
> test 7,8 and 10 were killed after running for more than 12 hoursI am using 
> the same script file for all tests. Is there a set of recommended options 
> that may apply to all ispd18 tests?
> Thanks
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail
