### ISSUE TITLE
utdBoxRouter fails on tsmc65lp lefs

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#7]
utdBoxRouter fails on opening the "merged" lef exported by innovus (using write_lef_library command). It contains the tech and the macros.

I let it run overnight and it generated 2.5GB of logs but no progress. I'm working on a simple gcd example design with no macros in the design, however the lef does include macros for memory/standard cells/pmk. 

Find attached the logs for gcd

[gcd_gr.log](https://github.com/billswartz7/UTD-BoxRouter/files/3187704/gcd_gr.log)

**Comment by billswartz7** [comment]
Have addressed the issues with lef class and multi ports.   Unfortunately, without the memories it is very difficult to insure that the issue is fixed.   Please reopen if it still fails.

**Comment by tajayi** [comment]
I tried the new build. I don't see the error messages after lef_read, however it doesn't seem to progress past that point. I've let it sit for about an hour now. I sent a sample lef that may exhibit some of the weirdness the tool doesn't handle

This seems to also be affecting utdTranslate.

**Comment by billswartz7** [comment]
Thanks for sending the snippet.  That was all I needed.   Now global router and translator are fixed as they had the same wrong code.

**Comment by tajayi** [comment]
Validated that I do not see this error when testing utd-translate
