### ISSUE TITLE
Documentation for gdo files

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#8]
Is it possible to have documentation on the parameters and commands in the gdo files? It's unclear what several of them are doing and how they affect. 

It would also be good to have a "recommended" gdo that should work reasonably well with all tscm65lp designs.

**Comment by billswartz7** [comment]
The command line and orparam Tcl commands have been documented and the README.md file has been updated to document how to use the global router.

**Comment by tajayi** [comment]
Great! Thanks
