### ISSUE TITLE
Router fails on simple tsmc65lp design

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#9]
The router fails on the simple gcd design, with def file is exported from innovus. I'll send the debug files seperately

```
[CDesign::Initialize]:design [gcd]
[CDesign::Initialize]:reading flute data.
[CDesign::read_lef]:reading LEF:./objects/cadre_tech_macro.lef...done...
[CDesign::read_def]:reading DEF:./objects/gcd_cadre_placed.def...
ERROR[CDesign::calc_pin_position]:(VDD P) pin does not have any geometries on a routing layer.  Defaulting to 1 at center.
ERROR[CDesign::calc_pin_position]:(VSS P) pin does not have any geometries on a routing layer.  Defaulting to 1 at center.
[CDesign::create_gcell_definitions]:GCELL origin: (7.200000, 7.200000)
[CDesign::create_gcell_definitions]:GCELL origin modified by user: (42.000000, 36.000000)
[CDesign::create_gcell_definitions]:GCELL custom xstep: 2.000000
[CDesign::create_gcell_definitions]:GCELL custom ystep: 3.000000
[CDesign::create_gcell_plane]:creating gcells...
[CDesign::create_gcell_plane]:done creating gcells...
[CDesign::read_def]:done reading DEF...
[CDesign::check_design]:There weren't any cells overlapping rows. Good!
[CDesign::calculate_routing_capacity]:pinlayer set to M2 (2)
ERROR[UTDcleanup]:System has detected an error in program:utdBoxRouter!
The program's process id=17201.
Please contact user support.

ERROR[UTDcleanupHandler]:Segmentation fault
ERROR[UTDbacktrace]:backtrace:
utdBoxRouter() [0x8089ca]
utdBoxRouter() [0x800c7e]
/lib64/libc.so.6() [0x31a1432510]
utdBoxRouter() [0x4413fa]
utdBoxRouter() [0x46dfe9]
utdBoxRouter() [0x46de61]
utdBoxRouter() [0x40f4aa]
utdBoxRouter() [0x40e8c2]
utdBoxRouter() [0x43dc58]
utdBoxRouter() [0x6ca606]
utdBoxRouter() [0x768934]
utdBoxRouter() [0x768bc6]
utdBoxRouter() [0x45f54e]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x31a141ed1d]
utdBoxRouter() [0x40a8a9]
```

**Comment by billswartz7** [comment]
It looks like global router is trying to route VDD and VSS.  Is VDD and VSS explicitly in the global router?  I assume that you have a tie off somewhere in the design.   I think it is safe to avoid these two.  I will try to reproduce the problem here.

**Comment by billswartz7** [comment]
Is VDD and VSS explicitly in the global router?  Half awake.   Is VDD and VSS explicitly in the netlist?

**Comment by tajayi** [comment]
> Is VDD and VSS explicitly in the global router?
I don't understand the question. VDD and VSS are referenced in the def

Is VDD and VSS explicitly in the netlist?
The def has powerplanning done so there are stripes and rings already present in the def.  There are some references to VDD and VSS in the def

**Comment by billswartz7** [comment]
Hi Tutu,
I added some more debug code to the global router but I still don't know what is going on.   I output an error and I try to generate an answer to prevent a crash.  I don't know if I suceeded.

**Comment by tajayi** [comment]
The segfault remains the same. The only lines that seem to have changed are these

```
ERROR[CDesign::calc_pin_position]:(VDD P) pin for model:VDD:INOUT:POWER does not have any geometries on a routing layer.  Defaulting to 1 at center.
ERROR[CDesign::calc_pin_position]:(VSS P) pin for model:VSS:INOUT:GROUND does not have any geometries on a routing layer.  Defaulting to 1 at center.
```

Thanks

**Comment by billswartz7** [comment]
Hi Tutu! Thanks so much for sending the snippet.  The problem wasn't what I thought it was.   I was able to create a similar crash here on my simple test case.   I will have a fix shortly.   Thanks again.  This was very helpful :)

**Comment by billswartz7** [comment]
Added code to prevent the crash.   Now the global router should complete without crashing.  Next, we need to investigate the offending pins.   Please send a snipped of the power and ground pins found in the PINS section of the DEF.     I think I just need to make this a warning in the future but I want to understand it first   Thanks in advance.

**Comment by tajayi** [comment]
Validated Def was generated and the UCSD route guide was happy with gcd. Will be moving on to more testcases

Thanks Bill.
